### ISSUE TITLE
Loading of an integer variable via ld instead of lw

### ISSUE THREAD

**Issue by pd-fkie** [riscv-collab/riscv-gcc#336]
When using the [riscv-gnu-toolchain](https://github.com/riscv-collab/riscv-gnu-toolchain) to build the riscv-glibc, the compiler generates
an invalid load instruction to access an integer member of a struct.

The affected struct is `struct _IO_FILE` ([source](https://elixir.bootlin.com/glibc/glibc-2.33/source/libio/bits/types/struct_FILE.h#L49)) which has an integer as its first member:
```c
struct _IO_FILE
{
  int _flags;		/* High-order word is _IO_MAGIC; rest is flags. */

  /* The following pointers correspond to the C++ streambuf protocol. */
  char *_IO_read_ptr;	/* Current read pointer */
  
  // -- snip --
}
```
When closing a `FILE*` with `fclose()`, `_IO_new_file_close_it` gets invoked and tries to access
`_flags`:
```c
int
_IO_new_file_close_it (FILE *fp)
{
  int write_status;
  if (!_IO_file_is_open (fp))
    return EOF;

  if ((fp->_flags & _IO_NO_WRITES) == 0
      && (fp->_flags & _IO_CURRENTLY_PUTTING) != 0)
    write_status = _IO_do_flush (fp);
    
  // -- snip --
}
```
But the instruction to access `_flags` is:
```
ld      a5,0(a0)
```
In all other functions accessing `_flags` I have inspected, the compiler correctly generated an `lw` and on x86 it also uses `mov eax, DWORD PTR [rdi]`.

Why does gcc generate an `ld` in this specific function? Is this a compiler bug? If not, can I tune riscv-gcc to use `lw` instead?

I'm using a custom RISC-V emulator with byte-level permissions, which means that everytime `fclose()` is called the emulator throws an error because it accesses the uninitialized padding bytes between `_flags` and `_IO_read_ptr`.

My toolchain setup is as follows:   
riscv-gnu-toolchain commit 051b9f7ddb7d136777505ea19c70a41926842b96
```
mkdir toolchain
./configure --prefix=$PWD/toolchain --with-arch=rv64iafd --disable-gdb
make linux
```
Then the command
```
./toolchain/bin/riscv64-unknown-linux-gnu-objdump -j .text --disassemble='_IO_file_close_it@@GLIBC_2.27' ./toolchain/sysroot/lib/libc.so.6 | head -n 16 | tail -n 1
```
yields the invaild instruction.

**Comment by cmuellner** [comment]
I've simplified the example to the following:
```c
#define FOO1 1
#define FOO2 2

struct s
{
  int f;
  char *p;
};

int
foo (struct s *p)
{
    if ((p->f & FOO1) == 0
        && (p->f & FOO2) != 0)
        return 1;
    return 0;
}
```

This results in the following for RV64
```asm
foo:
        ld      a0,0(a0)
        andi    t0,a0,3
        addi    t1,t0,-2
        seqz    a0,t1
        ret
```

On RV32 this results in:
```asm
foo:
        lw      a0,0(a0)
        andi    a0,a0,3
        addi    a0,a0,-2
        seqz    a0,a0
        ret
```

On AArch64 this results in:
```asm
foo:
        ldr     x0, [x0]
        and     x0, x0, 3
        cmp     x0, 2
        cset    w0, eq
        ret
```

> Is this a compiler bug?

No. If we remove the field `p` from the struct, then we get the following on RV64:

```asm
foo:
        lw      a0,0(a0)
        andi    a0,a0,3
        addi    a0,a0,-2
        seqz    a0,a0
        ret
```

And the following for AArch64:
```asm
foo:
        ldr     w0, [x0]
        and     w0, w0, 3
        cmp     w0, 2
        cset    w0, eq
        ret
```

So there is no read beyond the struct.
And reading too much data is irrelevant for correctness because the `andi` instruction will mask the irrelevant bits.

> Why does gcc generate an ld in this specific function?

The code is lowered to the following Gimple code (by the front-end):
```
  if ((BIT_FIELD_REF <*p, 64, 0> & 3) == 2)
    {
      return 1;
    }
  return 0;
```

If we shrink the data type by eliminating the field `char* p`, the lowered Gimple is:
```
  if ((BIT_FIELD_REF <*p, 32, 0> & 3) == 2)
    {
      return 1;
    }
  return 0;
```

So, it is the front-end, that decides that we have a 64-bit access here.

> If not, can I tune riscv-gcc to use lw instead?

I am not aware of a mechanism that exists already.

However, I can see three ways to handle that:
* look into the front-end and find out why it decides to use a BIT_FIELD_REF with a width of 64-bits and adjust that decision logic
* narrow the load-width in the `BIT_FIELD_REF` expansion
* add an optimization that narrows the load-width if the value is only used by an and-width-immediate

**Comment by aswaterman** [comment]
As Christoph wrote, GCC is within its rights to emit code that accesses the adjacent bytes. You’d need to make use of e.g. volatile to guarantee the desired behavior.

**Comment by jim-wilson** [comment]
Setting SLOW_BYTE_ACCESS to 0 should stop this.  See gcc/config/riscv/riscv.h.  The aarch64 port sets this to 1 like the RISC-V port does, the arm and x86 ports set it to 0.  I would expect that setting it to 0 results in worse code, but it isn't obvious what exactly the effect would be.  It may be a small effect.  The choice for the RISC-V port was made long ago, and probably never tested after that.  RISC architecture parts do normally set this to 1.  MIPS, SPARC, and PPC also all set it to 1 for instance.

The code emitted by gcc is OK.  The bytes do exist, and gcc isn't using the values in them.  GCC doesn't have any optimizer support for avoiding accidental references to padding bytes in the middle of a structure.  Other than what SLOW_BYTE_ACCESS does.

GCC is using the largest possible load size here because a 64-bit load is just as fast as a 32-bit load on a 64-bit machine (assuming 64-bit buses which is reasonable), and using a larger load size makes it possible to perform optimizations if we happen to also use the adjacent bytes.

The exact place where this choice is made is bit_field_mode_iterator::prefer_smaller_modes in stor-layout.cc. (or stor-layout.c in sources more than a month or two old).  This is called from get_best_mode.
