### ISSUE TITLE
How can I  use objdump to dump a flat binary file ????

### ISSUE THREAD

**Issue by yuyang-ok** [riscv-collab/riscv-gcc#340]
just like the intel cpus.
https://9to5answer.com/disassembling-a-flat-binary-file-using-objdump

**Comment by jim-wilson** [comment]
In the referenced URL, it mentions the need for a -m option.  For RISC-V, you have three choices for the -m option: riscv:rv32, riscv:rv64. and riscv.  Plain riscv defaults to riscv:rv64 so that won't give the right result if you have compressed instructions.  So you want -m riscv:rv32.  Otherwise the info in that URL should work fine for RISC-V.  Ignore the -M comments which are x86 specific.

riscv32-unknown-elf-objdump -b binary -m riscv:rv32 -D file.bin

**Comment by yuyang-ok** [comment]
@jim-wilson  thanks very much....
